version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
    # Locked to keep compatibility with .NET 8 and the following SDKs
    # Only allow patches
    - dependency-name: "Microsoft.CodeAnalysis.CSharp"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
