categories:
  - title: '🚀 Features & improvements'
    labels:
      - 'feature'
      - 'enhancement'
      - 'documentation'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance & dependencies'
    labels:
      - 'dependencies'
      - 'maintenance'
exclude-labels:
  - 'skip-changelog'
template: |
  ## What’s Changed

  $CHANGES
