language: csharp
mono: none
dotnet: 2.2.101
branches:
  only:
  - master
  - /release-.*/
  - /^\d+\.\d+\.\d+(-\S*)?$/
script: "./build.sh"
env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true NUGET_XMLDOC_MODE=skip
git:
  depth: false
matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx