version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/src"
    update_schedule: "live"
  - package_manager: "dotnet:nuget"
    directory: "/targets"
    update_schedule: "live"
