using System.ComponentModel;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using ServiceComposer.AspNetCore;

namespace Snippets.Contractless.CompositionHandlers;

// Stub interface representing a user-defined service
interface IMyService { }

// begin-snippet: contract-less-handler-from-services
[CompositionHandler]
class SampleCompositionHandlerWithServices
{
    [HttpGet("/sample/{id}")]
    public Task SampleMethod(int id, [FromServices] IMyService myService)
    {
        return Task.CompletedTask;
    }
}
// end-snippet

// begin-snippet: contract-less-handler-from-services-generated
// <auto-generated/>
#pragma warning disable SC0001
[EditorBrowsable(EditorBrowsableState.Never)]
class SampleCompositionHandlerWithServices_SampleMethod_int_id_IMyService_myService(
    SampleCompositionHandlerWithServices userHandler) : ICompositionRequestsHandler
{
    [HttpGetAttribute("/sample/{id}")]
    [BindFromRoute<int>("id")]
    [BindFromServices<IMyService>("myService")]
    public Task Handle(HttpRequest request)
    {
        var ctx = HttpRequestExtensions.GetCompositionContext(request);
        var arguments = ctx.GetArguments(this);
        var p0_id = ModelBindingArgumentExtensions.Argument<int>(arguments, "id", BindingSource.Path);
        var p1_myService = ModelBindingArgumentExtensions.Argument<IMyService>(arguments, "myService", BindingSource.Services);

        return userHandler.SampleMethod(p0_id, p1_myService);
    }
}
#pragma warning restore SC0001
// end-snippet
