name: MarkdownSnippets
on:
  workflow_dispatch:
jobs:
  documentation:
    name: Process documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Run MarkdownSnippets
      run: |
        dotnet tool install --global MarkdownSnippets.Tool
        mdsnippets ${GITHUB_WORKSPACE} -c InPlaceOverwrite
        git add .
      shell: bash
    - name: Fix links
      run: find ${GITHUB_WORKSPACE} -name "*.md" -not -name "*.source.md" -type f -exec sed -i '6,$s/\.source\.md/\.md/g' {} \;
      shell: bash
    - name: Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff-index --quiet HEAD || git commit -m "docs: update markdown snippets" && git push
