name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.2
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PR_CONCURRENT_LIMIT: 0
